### ISSUE TITLE
Server Files

### ISSUE THREAD

**Issue by leksmar** [mmmthepotatogod/the_multipack#1]
Will you add server files to curseforge?

**Comment by mmmthepotatogod** [comment]
> Will you add server files to curseforge?

hi leksmar!
first of all, thanks for being the first to ask something in this page!! :)
second of all, the modpack currently has some mods incompatibe with a multiplayer server.....(client side mods) (yes i tested it)
if you want, i can try my best to create a server file for every modpack file.
note 2 things:
1. it will make uploading normal modpack files much slower, cause ill need to test every version
2. there might be many bugs on servers..... (the pack is also in alpha/beta level, with many things to be changed, added, or removed)
3. as im the only one working on this, while trying to update the pack as frequently as possible, i will (probably) not do it, unless more people will want it. (actually, im working on an update right now!)
hope you understand my answer, since its currently 1:00 and my brain is empty :))
btw are you trying to play this with friends??

**Comment by leksmar** [comment]
Yea, we have group of ~6 friends and were looking for new modpack. Your modpack took our attention but I couldn't find server files and now I know the reason why. Hope more people will want to play with their friends too and u will make multiplayer update!

**Comment by mmmthepotatogod** [comment]
> Yea, we have group of ~6 friends and were looking for new modpack. Your modpack took our attention but I couldn't find server files and now I know the reason why. Hope more people will want to play with their friends too and u will make multiplayer update!

understood.
i have been to that point already :0 (and could not make the server run without lag, big sad)
ill try my best to create a server file for you guys!
2 things to ask:
1. why did my pack take your attention? (thanks btw :) ). i only have ~700 downloads, why not trying smt popular?
2. are you hosting the server on a site (like server pro and aternos) or on a local computer (or server)?

**Comment by leksmar** [comment]
1. Uhm, I need to ask my friend how she found this pack XD. The reason why we choose your pack is combination of tech mods (which I love) and adventures mods (which my friends love)+we finished many of popular packs and trying to find something different. 
PS There is added Refined Storage and not trash Applied Energetics
PPS There is an answer from my friend "I was looking for a fresh modpack because others are really similar, I tried 6 different modpacks and only this distinguished oneself. It's one of the few modpacks that actually has a lot of content"
2. We prefer to hosting on a site not server/local pc

**Comment by mmmthepotatogod** [comment]
RS is the beloved storage mod, isn't it? :)
well, now i can't let you down!
ill start working right away :)

**Comment by mmmthepotatogod** [comment]
> Will you add server files to curseforge?

DONE!
there is now a file (under review) for the server players!
if there is any other bug, question or suggestion, please feel free to let me know!
also, please note that the custom endgame is still WIP and does'nt have any recpies and stuff :(
ill work on it too :))

**Comment by leksmar** [comment]
Uhm, I'm note sure but u probably added server files as new modpack version

**Comment by mmmthepotatogod** [comment]
> Uhm, I'm note sure but u probably added server files as new modpack version

Yes, i added it to the curseforge page (as a new version)
It is called "the multipack server file"

**Comment by leksmar** [comment]
Yea, I mean with the next updates u could add it as a server files (idk if u can or u need more updates)

**Comment by mmmthepotatogod** [comment]
> Yea, I mean with the next updates u could add it as a server files (idk if u can or u need more updates)

Actually, im running out of update ideas....
Sure, ill try making server updates for the multipack! :)
Any cool idea for things to add or change? Im open for ideas 😁💡

**Comment by mmmthepotatogod** [comment]
> Yea, we have group of ~6 friends and were looking for new modpack. Your modpack took our attention but I couldn't find server files and now I know the reason why. Hope more people will want to play with their friends too and u will make multiplayer update!

yooooo have you played yet?

**Comment by leksmar** [comment]
Yep, we find out that u can give indestructible to one of ring from quests that revive u after death, and be immune to death forever

**Comment by mmmthepotatogod** [comment]
> Yep, we find out that u can give indestructible to one of ring from quests that revive u after death, and be immune to death forever

Wait what??
Do you mean the soulstone?
I thought I removed it 😧
Welp, more work for me 😕🤣
Anyways, is it fun? Im currently working on making new items, since I don't have any ideas for thing to update...

**Comment by leksmar** [comment]
Yea, it's enjoyable, maybe it's not the best pack I've ever played but for sure I don't feel I'm wasting time playing on it

**Comment by mmmthepotatogod** [comment]
> Yea, it's enjoyable, maybe it's not the best pack I've ever played but for sure I don't feel I'm wasting time playing on it

Yea i know, it's a new pack (with a new developer) 😃.
Have some ideas to make the pack cooler and nicer?

**Comment by leksmar** [comment]
probably hardest craftings for material berries, gobber plants (they scale too much with nature's blessing enchant or even bonemeal)

**Comment by mmmthepotatogod** [comment]
> probably hardest craftings for material berries, gobber plants (they scale too much with nature's blessing enchant or even bonemeal)

Already done :)
Also mad many other recipes harder!
Try updating the pack tomorrow?
